"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '$directory$git_branch$git_status$character'

[character]
success_symbol = '[❯](bold cyan)'
error_symbol = '[❯](bold red)'

[directory]
format = '[$path]($style) '
style = "bold blue"
truncation_length = 8

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = "purple"

[git_status]
format = '([$all_status$ahead_behind]($style)) '
